trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectDirectory: 'src/Eris.SmartCodeGenerator.ImmutableGenerator' 

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(projectDirectory)/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '$(projectDirectory)/*.csproj'
    configuration: '$(buildConfiguration)'
    includesymbols: true
    versioningScheme: 'off'
    verbosityPack: 'Normal'

- task: DotNetCoreCLI@2
  displayName: Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'

