trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectDirectory: 'src/Eris.SmartCodeGenerator.ImmutableGenerator' 

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(projectDirectory)/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Pack
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'pack'
    packagesToPack: '$(projectDirectory)/*.csproj'
    configuration: '$(buildConfiguration)'
    includesymbols: true
    versioningScheme: 'off'
    verbosityPack: 'Normal'

- task: PublishBuildArtifacts@1
  displayName: Publish
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    ArtifactName: 'smartcodegenerator-immutablegenerator-nupkg'
    publishLocation: 'Container'
