//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eris.SmartCodeGenerator.ImmutableGenerator.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImmutableConstructorTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImmutableConstructorTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eris.SmartCodeGenerator.ImmutableGenerator.Tests.ImmutableConstructorTestCases", typeof(ImmutableConstructorTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using Eris.SmartCodeGenerator.ImmutableGenerator;
        ///
        ///namespace Eris.SmartCodeGenerator.ImmutableGenerator.Tests.ImmutableConstructorTestCaseData
        ///{
        ///    [ImmutableConstructor]
        ///    public partial class TestObject
        ///    {
        ///        public uint Id { get; }
        ///        public string Name { get; }
        ///    }
        ///}.
        /// </summary>
        internal static string GetOnlyProperties {
            get {
                return ResourceManager.GetString("GetOnlyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using Eris.SmartCodeGenerator.ImmutableGenerator;
        ///
        ///namespace Eris.SmartCodeGenerator.ImmutableGenerator.Tests.ImmutableConstructorTestCaseData
        ///{
        ///    [ImmutableConstructor]
        ///    public partial class TestObject
        ///    {
        ///        public uint Id { get; }
        ///        public string Name { get; }
        ///    }
        ///}.
        /// </summary>
        internal static string GetOnlyProperties_Transformed {
            get {
                return ResourceManager.GetString("GetOnlyProperties_Transformed", resourceCulture);
            }
        }
    }
}
